[workspace]
resolver = "2"
members = [
    "server",
]

[profile.release]
lto = true

[workspace.dependencies]
anyhow = "1.0"
flexi_logger = "0.28"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.37", features = ["full"] }
